title: Wie sichern wir unsere digitale Identität
description: > 
  Projekt für die IdPA.
baseurl: ""
url: "" 

github_username: martyschaer

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
